# Generated by Django 5.2.7 on 2025-10-28 12:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tl_agents', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'permissions': (('export_schedule', 'Може експортувати розклад'),),
            },
        ),
        migrations.CreateModel(
            name='HistoricalShift',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(db_index=True)),
                ('direction', models.CharField(choices=[('calls', 'Дзвінки'), ('tickets', 'Тікети'), ('chats', 'Чати')], default='calls', max_length=20)),
                ('status', models.CharField(choices=[('work', 'Робоча зміна'), ('day_off', 'Вихідний'), ('vacation', 'Відпустка'), ('sick', 'Лікарняний'), ('training', 'Тренінг'), ('meeting', 'Мітинг'), ('onboard', 'Онборд')], default='work', max_length=20)),
                ('activity', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.agent')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical shift',
                'verbose_name_plural': 'historical shifts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(db_index=True)),
                ('direction', models.CharField(choices=[('calls', 'Дзвінки'), ('tickets', 'Тікети'), ('chats', 'Чати')], default='calls', max_length=20)),
                ('status', models.CharField(choices=[('work', 'Робоча зміна'), ('day_off', 'Вихідний'), ('vacation', 'Відпустка'), ('sick', 'Лікарняний'), ('training', 'Тренінг'), ('meeting', 'Мітинг'), ('onboard', 'Онборд')], default='work', max_length=20)),
                ('activity', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.agent')),
            ],
            options={
                'ordering': ['-start'],
                'permissions': (('import_schedule', 'Може імпортувати базовий розклад'), ('export_schedule', 'Може експортувати розклад')),
            },
        ),
        migrations.CreateModel(
            name='HistoricalShiftExchange',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_shift', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.shift')),
                ('to_shift', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.shift')),
            ],
            options={
                'verbose_name': 'historical shift exchange',
                'verbose_name_plural': 'historical shift exchanges',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ShiftExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('from_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex_from', to='core.shift')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex_to', to='core.shift')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': (('request_exchange', 'Може створювати запити на обмін'), ('approve_exchange', 'Може погоджувати/відхиляти обміни'), ('view_exchange_history', 'Може бачити історію обмінів')),
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['agent', 'start', 'end'], name='core_shift_agent_i_a20cfb_idx'),
        ),
    ]
