# Generated by Django 5.2.7 on 2025-10-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['user__username'], 'permissions': (('export_schedule', 'Може експортувати розклад'),)},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-start'], 'permissions': (('import_schedule', 'Може імпортувати базовий розклад'), ('view_predprod', 'Може переглядати predprod розклад'), ('view_prod', 'Може переглядати prod розклад'))},
        ),
        migrations.AlterModelOptions(
            name='shiftexchange',
            options={'ordering': ['-created_at'], 'permissions': (('request_exchange', 'Може створювати запити на обмін'), ('approve_exchange', 'Може погоджувати/відхиляти обміни'), ('view_exchange_history', 'Може бачити історію обмінів'))},
        ),
    ]
