# Generated by Django 5.2.7 on 2025-10-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshift',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
