# Generated by Django 5.2.7 on 2025-10-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_agent_options_alter_shift_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-start'], 'permissions': (('import_schedule', 'Може імпортувати базовий розклад'), ('export_schedule', 'Може експортувати розклад'), ('view_predprod', 'Може переглядати predprod розклад'), ('view_prod', 'Може переглядати prod розклад'))},
        ),
    ]
