# Generated by Django 5.2.7 on 2025-10-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_historicalshift_comment_alter_shift_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshift',
            name='status',
            field=models.CharField(choices=[('work', 'Робоча зміна'), ('day_off', 'Вихідний'), ('vacation', 'Відпустка'), ('sick', 'Лікарняний'), ('training', 'Тренінг'), ('meeting', 'Мітинг'), ('onboard', 'Онборд'), ('mentor', 'Менторство')], default='work', max_length=20),
        ),
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('work', 'Робоча зміна'), ('day_off', 'Вихідний'), ('vacation', 'Відпустка'), ('sick', 'Лікарняний'), ('training', 'Тренінг'), ('meeting', 'Мітинг'), ('onboard', 'Онборд'), ('mentor', 'Менторство')], default='work', max_length=20),
        ),
    ]
