# Generated by Django 5.2.7 on 2025-10-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shift_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-start'], 'permissions': (('import_schedule', 'Може імпортувати базовий розклад'), ('export_schedule', 'Може експортувати розклад'))},
        ),
        migrations.RemoveIndex(
            model_name='shift',
            name='core_shift_is_base_218fb5_idx',
        ),
        migrations.RemoveField(
            model_name='historicalshift',
            name='is_baseline',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='is_baseline',
        ),
    ]
